name: alrino
description: "Проект Алрино.DATA"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

#com.hpace.alrino
#Алрино.DATA

version: 1.20.0+1
# изменить имя
# AndroidManifest.xml (located at android/app/src/main
# <application android:label="App Name" ...>
# info.plist (located at ios/Runner)
# <key>CFBundleDisplayName</key>
# <string>App Name</string>

#обязательно для удаления очищения данных
# <application android:allowBackup="false"
# в файле AndroidManifest.xml

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  surf_lint_rules: ^3.0.0 #https://pub.dev/packages/surf_lint_rules
  cupertino_icons: ^1.0.6 #https://pub.dev/packages/cupertino_icons
  flutter_bloc: ^8.1.3 #https://pub.dev/packages/flutter_bloc
  bloc: ^8.1.2 #https://pub.dev/packages/bloc
  equatable: ^2.0.5 #https://pub.dev/packages/equatable
  flutter_svg: ^2.0.9 #https://pub.dev/packages/flutter_svg
  # flutter_native_splash: ^2.3.8 #https://pub.dev/packages/flutter_native_splash
  shared_preferences: ^2.2.2 #https://pub.dev/packages/shared_preferences
  flutter_launcher_icons: ^0.13.1 #https://pub.dev/packages/flutter_launcher_icons
  go_router: ^12.1.3 #https://pub.dev/packages/go_router
  google_fonts: ^6.1.0 #https://pub.dev/packages/google_fonts
  get: ^4.6.6 #https://pub.dev/packages/get
  bottom_sheet: ^4.0.0 #https://pub.dev/packages/bottom_sheet
  popup_menu: ^2.0.0 #https://pub.dev/packages/popup_menu
  dio: ^5.4.0 #https://pub.dev/packages/dio
  auto_size_text: ^3.0.0 #https://pub.dev/packages/auto_size_text
  flutter_feather_icons: ^2.0.0 #https://pub.dev/packages/flutter_feather_icons
  page_transition: ^2.1.0 #https://pub.dev/packages/page_transition
  # flutter_secure_storage: ^9.0.0 #https://pub.dev/packages/flutter_secure_storage
  mask_text_input_formatter: ^2.7.0 #https://pub.dev/packages/mask_text_input_formatter
  gap: ^3.0.1 #https://pub.dev/packages/gap
  flutter_typeahead: ^5.0.1 #https://pub.dev/packages/flutter_typeahead
  calendar_date_picker2: ^0.5.3 #https://pub.dev/packages/calendar_date_picker2
  intl: ^0.19.0 #https://pub.dev/packages/intl
  syncfusion_flutter_datagrid_export: ^24.1.41 #https://pub.dev/packages/syncfusion_flutter_datagrid_export
  syncfusion_flutter_datagrid: ^24.1.41 #https://pub.dev/packages/syncfusion_flutter_datagrid
  analog_clock: ^0.1.1 #https://pub.dev/packages/analog_clock
  speech_to_text: ^6.5.1 #https://pub.dev/packages/speech_to_text
  permission_handler: ^11.2.1 #https://pub.dev/packages/permission_handler
  path_provider: ^2.1.1 #https://pub.dev/packages/path_provider
  flutter_table: ^1.1.0 #https://pub.dev/packages/flutter_table
  fullscreen_window: ^1.0.3 # https://pub.dev/packages/fullscreen_window
  open_file: ^3.3.2 # https://pub.dev/packages/open_file
  # file_picker: ^6.1.1
  syncfusion_flutter_xlsio: ^24.1.47 #https://pub.dev/packages/syncfusion_flutter_xlsio
  excel: ^4.0.2 #https://pub.dev/packages/excel
  flutter_switch: ^0.3.2 #https://pub.dev/packages/flutter_switch
  device_info_plus: ^9.1.2 #https://pub.dev/packages/device_info_plus
  flutter_easylogger: ^2.3.3 #https://pub.dev/packages/flutter_easylogger
  url_launcher: ^6.2.5 #https://pub.dev/packages/url_launcher
  flutter_network_connectivity: ^0.0.6 #https://pub.dev/packages/flutter_network_connectivity
  http: ^1.2.1    
  flutter_ringtone_player: ^4.0.0+2 #https://pub.dev/packages/flutter_ringtone_player 
  workmanager: ^0.5.2 #https://pub.dev/packages/workmanager
  flutter_local_notifications: ^17.1.2 #https://pub.dev/packages/flutter_local_notifications
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

dependency_overrides:
    flutter_lints: ^2.0.1

# flutter pub run flutter_launcher_icons:main
flutter_launcher_icons:
  android: ic_launcher
  ios: true
  remove_alpha_ios: true
  image_path: assets/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
